### ISSUE TITLE
Cannot turn off google analytics page tracking

### ISSUE THREAD

**Issue by SpoonMeiser** [asual/jquery-address#10]
jquery-address is automatically invoking google analytics, and is getting it wrong.

I think it makes much more sense for me to manage this manually, in my change callback, but I cannot see a way to tell jquery-address to not invoke pageTracker.

I would argue that, although helpful, doing this is orthogonal to jquery-address' purpose, and therefore should be optional.

**Comment by asual** [comment]
Have you tried including the script like this:
    <script type="text/javascript" 
        src="jquery.address-1.2.min.js?tracker=null">
    </script> 

Alternatively you can null the tracker using the API.

**Comment by SpoonMeiser** [comment]
Thanks for the quick response.

Neither of those methods seem to work. I assume that the API method is:

```
$.address.tracker(null);
```

This didn't make any difference.

Looking at the code, it looks like it looks to see if it has a custom tracker function first, and then falls back to looking for google analytics if it doesn't, so I tried setting tracker to be a harmless function:

```
$.address.tracker(function(val){alert("track: " + val);});
```

But this alert never gets triggered.

**Comment by SpoonMeiser** [comment]
I've misread the code.

Whereas in most places, _opts is read directly, when looking for a tracker function, it's accessed like this:

```
window[_opts.tracker]
```

Or, in the latest version:

```
_t[_opts.tracker]
```

where _t is either window or top.

If I'm understanding this correctly now, it means that to stop the default behaviour, I need to set tracker to be the name of a method of the window object.

For example, if I do this:

```
$.address.tracker('alert');
```

Then instead of the default tracker behaviour, I get an alert with the value that it would have sent to pageTracker.

Is this the intended behaviour?

**Comment by asual** [comment]
The _opts.tracker is a function name as a string. You can check the internal _track method to see how this case is handled. As long as the tracker parameter is not a valid function the GA tracking will not be called.

**Comment by SpoonMeiser** [comment]
I didn't know you could access objects as attributes of the window object like that.

However, the behaviour you describe isn't what I'm seeing, and it's not what I would expect from the code in the internal _track method either.

Paraphrased, it goes:

```
var fn = window[_opts.tracker];

if (typeof fn == FUNCTION)
    fn(value);
else
    ...default behaviour...
```

I might be reading the code wrong, as I've clearly already done once, but it looks to me like the default behavior (which includes the GA tracking) will only not be called if _opts.tracker _is_ a valid function name.

**Comment by asual** [comment]
You can read the code as you want but it looks like this:

```
_track = function() {
    var value = (_l.pathname + (/\/$/.test(_l.pathname) ? '' : '/') + 
        ($.address ? $.address.value() : '')).replace(/\/\//, '/').replace(/^\/$/, ''),
        fn = _t[_opts.tracker];
    if (typeof fn == FUNCTION) {
        fn(value);
    } else if (typeof urchinTracker == FUNCTION) {
        urchinTracker(value);
    } else if (typeof pageTracker != UNDEFINED && typeof pageTracker._trackPageview == FUNCTION) {
        pageTracker._trackPageview(value);
    } else if (typeof _gaq != UNDEFINED && typeof _gaq.push == FUNCTION) {
        _gaq.push(['_trackPageview', value]);
    }
}
```

**Comment by SpoonMeiser** [comment]
Yes, so given that the test on pageTracker will succeed, and the test on urchinTracker will fail, the only way to avoid GA tracking is for fn to be a function. Which means that setting trtacker to null doesn't stop GA tracking.

**Comment by asual** [comment]
You're correct. I modified the code to work as expected. Try the latest version.

**Comment by SpoonMeiser** [comment]
Sorry I've not been able to get back to you sooner. Yes, the change fixes my problem. Thank you.
