### ISSUE TITLE
$.address.value scrolls to top after _l.hash

### ISSUE THREAD

**Issue by ashclarke** [asual/jquery-address#102]
Hi asual,

As part of the `address.value` function the hash of the page is set in lines similar to: `_l.hash = '#' + _crawl(_value, TRUE)` (approx. line 489)

When I set `$.address.value("");`, I don't want the page to scroll to the top. 

To counter this, I tried setting `return false;` at the end of my `$.address.change(event)` function as well as `event.preventDefault();`.

I have also tried to override the `window.onhashchange` as per this link: http://stackoverflow.com/questions/4715073/window-location-hash-prevent-scrolling-to-the-top , but the page scrolls to the top before this function is even called.

I also tried using `$.address.wrap(true)` but this has other strange side effects (some of my functions do not initialise).

I have `h3` elements calling the `address.value` function via events assigned with jQuery `click()`.

Using Firefox 6.

Any help would be appreciated.

**Comment by asual** [comment]
The approach used in `$.address.wrap(true)` is the only good working solution for this case. It generates an additional DIV element around the content which preserves the scroll position. Can you adjust your code with that in mind? Please, post a sample function that fails to initialize when you use the wrap option.
