### ISSUE TITLE
_value != hash returns true if _value is an unencoded URI

### ISSUE THREAD

**Issue by eleith** [asual/jquery-address#104]
i was pushing values using <code>$.address.value()</code> that were triggering navigation changes twice. 

this was because the stored <code>hash</code> value was encoded while the <code>_value</code> was not encoded, causing <code>diff</code> to be true for values that had spaces in it.

i've forked the project and added the encoding option in the <code>_strict()</code> function since that is used throughout the project to update the <code>_value</code>. 

i've also made it an option so it can be turned off if needed.

https://github.com/eleith/jquery-address/commit/3c084d0209db577a63849dd421010d7f1481c9b0

**Comment by joksnet** [comment]
@eleith Can you push the changes to this repo ? That way @asual can merge and the project avance and everyone benefits. Meanwhile I have to apply this patch manually.
