### ISSUE TITLE
Changing iframe src adds additional history state

### ISSUE THREAD

**Issue by nickday** [asual/jquery-address#106]
Hi,

So I have a page which uses jQuery Address to load in various bits of data into various iframes within the page.  I am directly changing the the iframe src attribute like this:

$("#text").attr("src", "/something/");

This works fine, BUT it seems that changing the src of the iframe pushes an extra history state onto jQuery Address - as when I press Back after changing the address, I have to press it twice in order to get the iframe back to its original pre-address-change src.

Is this a bug, or is there a way around this?

Thanks,
Nick

**Comment by asual** [comment]
I believe this is a standard browser behavior that the plugin cannot prevent. You can try using the location.replace(src) method which by definition should not generate a history entry.

**Comment by nickday** [comment]
That works fine - many thanks for your help.
