### ISSUE TITLE
Dynamically added elements incorrectly reported as external changes

### ISSUE THREAD

**Issue by cnanney** [asual/jquery-address#11]
All commits past c8ba442b57489587d243 incorrectly treat dynamically created links as external changes instead of internal as they should be.

Also on this note - a feature request... I think it would be helpful if the $.address.change(fn) event, there was a way to determine if the change was internal or external.

**Comment by cnanney** [comment]
To clarify...
v1.2 - Date: 2010-03-27 14:50:00 +0200 (Sat, 27 Mar 2010) is the last version that does not have the bug, all subsequent commits have the bug.

**Comment by asual** [comment]
I wasn't able to reproduce the problem using the following code:

```
<!DOCTYPE html>
<html>
    <head>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.js"></script>
        <script type="text/javascript" src="http://github.com/asual/jquery-address/raw/master/dist/jquery.address-1.2.1.min.js"></script>
        <script type="text/javascript">
            $.address.internalChange(function(e) {
                console.info("internalChange:" + e.value);
            });
            $.address.externalChange(function(e) {
                console.info("externalChange:" + e.value);
            });
            $(function() {
                $('a').address().click(function(e) {
                    $('<a href="#dynamic">Test Dynamic</a>').appendTo(document.body);
                    $(this).unbind('click', arguments.callee);
                    return false;
                });
            });
        </script>
    </head>
    <body>
        <a href="#static">Test Static</a>
    </body>
</html>
```

**Comment by cnanney** [comment]
I'll try and extract a test case from my code that reproduces the problem. It happens in divs whose html content is loaded via ajax.

**Comment by cnanney** [comment]
With the following code:
    <!DOCTYPE html>
    <html>
        <head>
            <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.js"></script>
            <script type="text/javascript" src="http://github.com/asual/jquery-address/raw/master/dist/jquery.address-1.2.1.min.js"></script>
            <script type="text/javascript">
                $.address.internalChange(function(e) {
                    console.info("internalChange:" + e.value);
                });
                $.address.externalChange(function(e) {
                    console.info("externalChange:" + e.value);
                });
                $(function() {
                    $("#load").click(function() {
                        $.ajax({
                                type: "POST",
                                url: "ajax.html",
                                success: function(data){
                                    $("#ajax").html(data);
                                }
                            });
                      return false;
                    });
                });
            </script>
        </head>
        <body>
            <a id="load" href="#">Load Links</a>
            <div id="ajax"></div>
        </body>
    </html>

Loading this HTML via AJAX:

```
<a href="#something" rel="address:/deep-link">Internal Change</a><br />
<a href="#somethingelse" rel="address:/somethingelse">Internal Change</a><br />
<a href="#another" rel="address:/another">Internal Change</a><br />
```

Clicking the newly loaded links will log external changes to console.

**Comment by asual** [comment]
The problem is that the rel attribute of such dynamically loaded links is not handled in this case. I made it working for Ajax loaded content but in general the approach won't work for links that are created dynamically with a plain DOM manipulation.

Can you please test the latest source file?

**Comment by cnanney** [comment]
That fixed it. Links are now properly reporting as internal. Thank you!

**Comment by ramimawas** [comment]
I am having the exact same problem. I am using this version:
jQuery Address Plugin v1.2rc

jQuery is :
jQuery JavaScript Library v1.4.4
