### ISSUE TITLE
Google Analytics has repeated request on first open URL, cased bug after revision @f0255d1aaa

### ISSUE THREAD

**Issue by laukstein** [asual/jquery-address#112]
@asual your latest commit @f0255d1aaa cases GA plugin repeated request on first open URL.
You can check in live in http://lab.laukstein.com/ajax-seo/

**Comment by asual** [comment]
Are you sure that this wasn't happening before? The plugin has always invoked the GA code when a change occurs so that it can track the proper page and not the root one. Because of this you should include a modified GA code that doesn't call _trackPageview.

**Comment by laukstein** [comment]
Before @f0255d1 `/ajax-seo/url` was causing one GA request and XHR `/ajax-seo/api/url` (but there was no need for first open url **XHR**, https://github.com/asual/jquery-address/issues/56#issuecomment-3472782).
After @f0255d1 **XHR** issue has been fixed, but is causing a new bug with GA - repeated GA request caused by jquery.address.js Any issue?

**Comment by asual** [comment]
I have just updated the State sample on asual.com but I still cannot see the issue. Can you please try to reproduce it with http://www.asual.com/jquery/address/samples/state/ and give me more details if it's browser or scenario specific.

**Comment by laukstein** [comment]
Also http://www.asual.com/jquery/address/samples/state/ will case the same bug (repeated GA request on first open url) if you'll try to add in your GA snippet `_trackPageview`.
For now I removed `_trackPageview`, but as I know, GA would expect to use `_trackPageview` by default.

Any better solution?

**Comment by asual** [comment]
The default _trackPageview will always track the root page and this is something that you don't want when you use such a deep linking technique. The plugin will call it automatically and will track the proper address. This is exactly what I tried to explain in the first comment.

**Comment by laukstein** [comment]
Fallow @mathiasbynens [comment](http://mathiasbynens.be/notes/async-analytics-snippet#comment-78): Unfortunately, `_trackPageview` is required to send the data to Google Analytics. If you run your snippet from the console, and keep an eye on the Network tab in your browser’s developer tools, you’ll see that the utm.gif beacon is never requested.

Latest jQuery Address still cases repeted GA  __utm.gif request for the first page load.
You are welcome to reopen this ticket since it seems to be relevant.
