### ISSUE TITLE
ie browser is not supported the pushState

### ISSUE THREAD

**Issue by pandikamal** [asual/jquery-address#114]
hi 
this is my code:

 var init = true, 
      state = window.history.pushState !== undefined;

```
$.address.state('/rw2011')
         .init(function(){
                        $('a.rwajax').address();
            })         
         .change(function(event) {
             var qstring = '';
             if(event.queryString != ''){
                qstring = '?' +  event.queryString;
             }


             if (state && init) {

                                 init = false;

                          } else {

                var url = $.address.state() + event.path + qstring;
                     load_page(url+' #inside','div#inside');
            }
        });
```

it support all modern browser with except IE browser. my url is http://localhost/rw2011/contact-us but ie browser should be http://localhost/rw2011/#/contact-us, here how to remove the hash /#  in this url.

please help me, couple of weeks, i have to analysis this issue.

**Comment by asual** [comment]
IE doesn't support HTML5 pushState and there is nothing we can do about it. IE10 will introduce such support.
