### ISSUE TITLE
$.address.change() loading twice in browsers except mozilla

### ISSUE THREAD

**Issue by pandikamal** [asual/jquery-address#119]
hi,
this is my code

 var init = true, 
         state = window.history.pushState !== undefined;
    $(document).ready(function(){

```
    $('a.rwajax').live('click', function(event){
        event.preventDefault();
                   return false;
    });

    $.address.state('/rw2011')
              .init(function(){$('a.rwajax').address(function(){return getUri($(this).attr('href'));});})
              .change(function(event){
                  alert('hi');
              });
      });
```

please help me, what i am missing that code.

**Comment by pandikamal** [comment]
i understood, why this should be loading twice means, i have initialized the dom ready again, that was the problem its loading twice. so i removed $(document).ready(function(){}); its working fine.

**Comment by asual** [comment]
Yes, the plugin is not designed to work inside the document ready function. I will probably have to enable that in the future.
