### ISSUE TITLE
new tab broken

### ISSUE THREAD

**Issue by DusanMilko** [asual/jquery-address#12]
in example
right clik on a tab and clik open in new tab,
leads to a broken page.

example:
start here;
http://www.asual.com/jquery/address/samples/tabs/#/extras.html
right click and open new tab on overview,
takes u here: page it missing content.
http://www.asual.com/jquery/address/samples/tabs/#Overview
should take u here;
http://www.asual.com/jquery/address/samples/tabs/#

**Comment by asual** [comment]
Due to some limitations of the jQueryUI widget I had to fix this in a not that perfect way. You should always have a hash fragment for the tab links and therefore the first tab will have both a "#" and "#Overview" deep link. I can try later to hide the first one.

**Comment by DusanMilko** [comment]
its not about the url,
http://www.asual.com/jquery/address/samples/tabs/#Overview
has no content in it,
whereas 
http://www.asual.com/jquery/address/samples/tabs/#
has content in it,

another example,
start at:
http://www.asual.com/jquery/address/samples/tabs/
when u clik to features,
it loads up features content and url is:
http://www.asual.com/jquery/address/samples/tabs/#/features.html
but if you go back and instead right click > open new tab on features
it loads empty content and url is:
http://www.asual.com/jquery/address/samples/tabs/#Features

**Comment by asual** [comment]
It's now fixed in the repository but still not deployed on asual.com. Pull the latest version and test locally.

**Comment by DusanMilko** [comment]
ok, thanks
