### ISSUE TITLE
Browser : IE 9 system : Win7 . Problem : $.address.state 

### ISSUE THREAD

**Issue by Lethea** [asual/jquery-address#122]
I've a problem with url changing in IE .
$.address.state('{app::base_href}').init(function() {
            // Initializes the plugin
            $('a.profileLink').address();

```
    })
```

when I open it in internet explorer , 
it turns that for example :
www.example.com/signup  to
www.example.com//#/signup 
where did the fking "#" come from ?
I search another website that use this or like this plugin .
for ie www.pinterest.com
they do that , if  the browser not  IE 
so the shared item opening in COLORBOX and url Changing
otherwise it goes to the real url not url tracking.
then I look at
hypem.com
they do the same .
www.hypem.com/popular/2
3 
4
if it is not Ie 
. but if IE 
the url not changing ? 
also they have the "#" problem

**Comment by asual** [comment]
Only IE 10 supports HTML5 pushState which allows you to change the address without using hashes. The behavior you're experiencing is a fallback mechanism for browsers that don't support pushState.
