### ISSUE TITLE
Does this work with jQuery 1.7.x now?

### ISSUE THREAD

**Issue by trusktr** [asual/jquery-address#124]
By the way, sweet plugin! Thank you!!!

**Comment by paulm17** [comment]
Yes, I am using this with 1.7.x just fine.  However, the plugin still uses .attr instead of .prop.

**Comment by trusktr** [comment]
Sweeeet. For a long while, it was broken for version of jQuery higher than 1.4.4.

**Comment by b9chris** [comment]
jquery.address 1.4 works in jquery 1.7.2 and below. It does not work in jquery 1.8.x.

**Comment by amakaa** [comment]
I downloaded the 1.5 version and it's still not working with jquery 1.7. Is there something I have to modify?
