### ISSUE TITLE
Can't retrieve data submit via POST

### ISSUE THREAD

**Issue by jcldavid** [asual/jquery-address#128]
``` javascript
$('form').address(function(){
    return $(this).attr('action');
});

```

``` javascript
$.ajax({
        data: $('form').serialize(),
        type: 'POST',
        url:  submit.php,
        beforeSend: function () {
                ...
        },
        success: function (data, textStatus, jqXHR) {
                ...
        },
        error: function (jqXHR, textStatus, errorThrown) {
                ...
        }
});
```

``` php
<?php echo 'Post: '.print_r($_POST,true).'Get: '.print_r($_GET,true) ?>
```

and they contain nothing.

**Comment by b9chris** [comment]
Why are you calling jquery.address in that manner on the first 3 lines?

I have it tied into a site of ours, but I have it explicitly tied to links that follow a certain pattern and nothing else. It doesn't interfere with posting via jquery. Tying it to a form seems pretty strange.

Looking at the commit history for jquery.address it does appear there may have been code in it at one point to interrupt normal form submission, but that's been commented out. You might be following old and outdated documentation that leads to broken functionality.

If you look at the 1.4 version of the code, it checks to verify the tag it's responding to is a link tag, then continues with the functionality of the library; if it's not a link tag it just ties a click event handler in that returns nothing.

What you're trying to do shouldn't involve jquery.address. You want something more like

$('button').click(function(ev) {
  ev.preventDefault();
  $.ajax({
    url: '/url...',
    data: $('form').serialize()
    type: 'POST',
    dataType: 'json',
    contentType: 'application/json; charset=utf-8',
    success: function(r) {
      alert('You submitted it');
    },
    error: function(jqXhr, serverErrorText, jsException) {
      alert('Bad news');
    }
  });
});
