### ISSUE TITLE
Latest version not working on IE!!

### ISSUE THREAD

**Issue by BMCouto** [asual/jquery-address#131]
After all my assets are loaded I'm calling init() like this:

``` javascript
window.init = function() {
        console.log('inti');
        $.address.change(function(event) {
            console.log('address change');
```

In IE7 and IE8 that second console.log never fires which put the blames on address. Any idea of what might be causing this?

Thanks!

**Comment by asual** [comment]
I have never heard of window.init before. What is that? Is 1.4 the latest version you're testing against?

Move $.address.change out of any document ready or window load functions and it should work fine.

**Comment by b9chris** [comment]
Can we close this? It's not a legitimate bug report... .

**Comment by asual** [comment]
Done. Thanks!
