### ISSUE TITLE
Opera: Cannot convert $.address to object

### ISSUE THREAD

**Issue by apollox** [asual/jquery-address#133]
We use the 1.5 version of the plugin and this version work  not correctly with actual Opera versions. On our site where we use it throw Opera often the error "Cannot convert $.address to object", when a user comes the first time on the site. When the user already visit one page it give no errors, only on the first visit give it very often the error.

We load the plugin with the getScript method of jQuery in document.ready and in the getScript callback we call a function to initialize the plugin and there throw Opera the error.

``` javascript
function searchInitialize()
    {
        $.address.init(function(event)
        {
            $.address.crawlable(1);
            $.address.history(0);
        })
        .change(function(e)
        {
            // for anything that isn't homepage
            if (e.value != '/')
            {
                searchForKeyword(e.value);
            }
        })
    }
```

In all other browsers like firefox, chrome, safari and also IE work it without any problems.

**Comment by asual** [comment]
Can you please provide a simple test case demonstrating the issue? Can you also try the uncompressed version and let me know which line is the problematic one?

**Comment by apollox** [comment]
I can change tomorrow on work the version to the uncompressed version on the site. 
A simple test case is a little bit difficult, because the error comes not every time in opera. We have try to get the error self already and do not get it, but many visitors get it so that we get an error mail.
The site is www.brand-catcher.com

**Comment by apollox** [comment]
We found out that $.address is null or undefined in Opera. So the issue is not the plugin.
