### ISSUE TITLE
HTML 5 State and Browser Forward

### ISSUE THREAD

**Issue by ghost** [asual/jquery-address#135]
With state set, there seems to be a problem going forward (using browser history) into the jquery-address-enabled-page after going back to a previous page in the history.

I followed the state example (http://www.asual.com/jquery/address/samples/state) but instead of having the server return the full page to the $.ajax() call, the server only returns the fragment of the page that is necessary if the request has the "x-requested-with=XMLHttpRequest" header.

To produce the problem (experienced on FF12, Chrome14):
1. I open a starting point (e.g. google.com).
2. I then navigate to my jquery-address-enabled page
3. I click on an address enabled link
4. I press BACK twice to go back to my starting point (google.com)
5. I click FORWARD into the jquery address page

Once I get back to the page, the page only contains the page fragment that was returned by the last $.ajax() call and not the entire page that was there before I hit the back button (header, nav, footer, etc. all missing). This only happens if I go back to a previous page and try to go forward again. If I stay within the jquery address page, back and forward work as expected.

As I mentioned earlier, I've implemented the server differently than the server for the sample (http://www.asual.com/jquery/address/samples/state). This is to conserve bandwidth and not transfer more data than necessary (and to not generate header and footer content that we are just going to throw away). Is the $.ajax() call supposed to fetch the entire page or Is this a known limitation?

Thanks,
Andy

**Comment by asual** [comment]
The State sample is implemented like this just for simplicity. Something similar to what you describe is implemented for the Express sample: http://www.asual.com/jquery/address/samples/express/

Try reproducing the issue with the above sample. It sounds a little bit strange and can somehow related to caching. Do you experience it across different browsers?

**Comment by ghost** [comment]
You're absolutely right about caching being the issue. I took a look at the Express sample and there was a "cache: false" parameter being passed to the $.ajax() call. Adding this to the call resolved the issue.
