### ISSUE TITLE
consolidating jquery.address source code with other source code generates error with ant build

### ISSUE THREAD

**Issue by ctumolosus** [asual/jquery-address#138]
Hi,

At work we have a build which consolidates all the files for an application into  a single file. For unknown reasons, jquery.address adds weird characters to the file when consolidated. I don't know whether this is related to the fact that i can't pass url parameters to initialize the file. Is there a way to do this inline? I would appreciate if a solution is given to solve this problem.

If you would like to test, we are using ant with ant-contrib. The task called to consolidates all the files is "concat" with "fixlastline" attribute set to true. A simple scenario would be to consolidate jQuery, jQuery.Address, and any other file after that.

**Comment by asual** [comment]
Every setting that can be applied using query parameters can be set using plain JavaScript.

The weird characters thing can be something related to encoding but I have never heard of such a problem and I have seen the plugin being consolidated.

**Comment by b9chris** [comment]
Yes, check the encoding on the files you're concatenating. Either the way you're concatenating should be fixed to handle varying encodings, or the files you're concatenating should be modified to all use the same encoding.

I use Microsoft Ajax Minifier to concat jquery.address-1.4 in with jquery-1.7.2 and a number of other js code files and minify them, and the result works properly with no oddities; but ant may be more fragile, or you may have used an editor that saved out in an unusual encoding.
