### ISSUE TITLE
jQuery 1.8.0

### ISSUE THREAD

**Issue by awsp** [asual/jquery-address#139]
Just happened to upgrade from jQuery 1.7.2 to 1.8.0 this morning,
and it looks like jQuery.address has stopped working for 1.8.0. :(

**Comment by dewezlopez** [comment]
I can only replicate the issue in Chrome. All other browsers are working fine.

**Comment by asual** [comment]
I will check. Thanks for pointing this out!

**Comment by laukstein** [comment]
@asual, @awsp it works fine with updated [jquery.address.js](https://github.com/laukstein/ajax-seo/blob/master/images/jquery.address.js), a working demo in http://lab.laukstein.com/ajax-seo/
The issue might be related to my pull https://github.com/asual/jquery-address/pull/109 and jQuery [deprecating features](http://blog.jquery.com/2012/08/09/jquery-1-8-released/) `Deprecate .bind("ready") event`.

**Comment by ccarbonell** [comment]
Hello guys, don't you have any answer yet? I've got the same issue on chrome

**Comment by laukstein** [comment]
You can use updated code from https://github.com/laukstein/ajax-seo/blob/master/images/jquery.address.js and minified version https://github.com/laukstein/ajax-seo/blob/master/images/jquery.address.min.js - it works fine with jQuery 1.8 also on Chrome.
There might be issue also in the snippet, the one that works https://github.com/laukstein/ajax-seo/blob/ec53605b2c9ca8ad4cb6f4b6678a471de27e5ee1/index.php#L207-279

**Comment by ccarbonell** [comment]
Thank you very much for your help, I am currently testing, everything seems to be working ok after update jquery.address and jquery1.8.0

If I found any issue I will let you know.

Cheers.
