### ISSUE TITLE
Form sample: problem with special and blank character

### ISSUE THREAD

**Issue by FlashJunior** [asual/jquery-address#14]
Go to http://www.asual.com/jquery/address/samples/form/

Enter a String to input und textarea:
for example: "Test mit Sonderzeichen + - / = ÖÄÜ und Leerzeichen"

after "change event" you'll see "Test+mit+Sonderzeichen+%2B+-+%2F+%3D+ÖÄÜ+und+Leerzeichen" :-/

any idea?

**Comment by asual** [comment]
Sorry, I have this fixed for a almost 3 weeks but I still haven't pushed it because I'm thinking about the general encoding policy. Will try to finish it soon.

**Comment by asual** [comment]
Works fine now.

**Comment by asual** [comment]
The change is only applied in the GitHub repo. It will become a part of the 1.3 release and the samples on asual.com are still using 1.2.2.
