### ISSUE TITLE
Chrome + Latest jQuery

### ISSUE THREAD

**Issue by dewezlopez** [asual/jquery-address#142]
Chrome ver: 21.0.1180.79 m
Jquery ver: latest
Address: 1.4

```
$('.something').click(function (e) {    
    e.preventDefault();
    $.address.value("123");
});

$.address.change(function (event) { 
    myFunction(event.value.replace('/','')); 
}); 

```

Error returned is: "Cannot call method 'replace' of null" 

Was working fine earlier this month, works on all other browsers. 

Has anyone else dealt with this issue? Is there something I'm doing wrong? Could I be doing this differently?

Many Thanks,

V

**Comment by dewezlopez** [comment]
Update:

Latest jQuery in Chrome seems to be causing the issue. Reverting to jQuery 1.7.2 worked fine.

**Comment by asual** [comment]
Can you please try the 1.5 dev version of the plugin? I just updated the test case to use jQuery 1.8.0 and everything seems to work fine in my Chromium 21.0.1153.0.

**Comment by dewezlopez** [comment]
Works for me! Thanks asual.
