### ISSUE TITLE
Latest version not working on IE7

### ISSUE THREAD

**Issue by victmo** [asual/jquery-address#147]
The latest version of the code is not working on Internet Explorer 7.

I tested the following code on IE9, in IE7 and 8 mode (from the dev toolbar). IE9 and 8 worked fine, but when tested on IE7 `$.address.change` is only fired when the document loads.

I tried with jQuery version 1.7.0 to 1.8.0 and placed the function inside and outside `$(document).ready()`...

``` html
<html>
    <head>
        <title>jQuery Address Test</title>

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
        <!--script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script-->
        <script src='js/lib/jquery.address.js'></script>
        <script>
            //$(document).ready(function(){
                $.address.change(function(e){
                    alert(e.value);
                });
            //});
        </script>
    </head>

    <body>
        <ul>
            <li><a href="#/">#/</a></li>
            <li><a href="#/lorem">#/lorem</a></li>
            <li><a href="#/ipsum">#/ipsum</a></li>
        </ul>
    </body>
</html>
```

**Comment by asual** [comment]
Thanks! Can you please create a pull request that I can merge into the project.

**Comment by victmo** [comment]
Awesome, my first contribution to a Github project! Cheers.
