### ISSUE TITLE
uncomfortable "#/" in Browsers like Firefox, Opera, Chromium

### ISSUE THREAD

**Issue by ghost** [asual/jquery-address#149]
In at least Firefox, Opera, Chromium such code like
  $.address.parameter("a", "x");
produces
  domain/#/?a=x
instead of
  domain/?a=x
and with given url domain/?a=y
  domain/?a=y#/?a=x
results which is very uncomfortable.
Browser:
  Firefox 15.0.1
  Opera 12.02
  Chromium 20.0.1132.47
OS:
  Linux Lubuntu 12.04
JQuery Address 1.5

**Comment by asual** [comment]
This is how the plugin works if you don't use the state option which relies on the HTML5 pushState API. It's supported by all the browsers you mentioned and IE10.
