### ISSUE TITLE
Let the ability to set function as the tracker option (Fix incldued)

### ISSUE THREAD

**Issue by nyroDev** [asual/jquery-address#15]
Currently, we can only set a strong representing a function defined in the window object as the tracker, using the $.address.tracker(value); function.

In my current project which is relly important regarding memory leak and other stuff, we don't want to create many and many function in the window object.

The idea here is to check in the _track function if the _opts.tracker is a function or not. If it is, just use it directly. If not, just use the  current beahvior.

THE FIX ::
On line 113, we have :
var fn = _t[_opts.tracker],

Just replace it by :
var fn = $.isFunction(_opts.tracker) ? _opts.tracker : _t[_opts.tracker],

and we're done.

Thanks a lot for your plugin, and including this fix will be great for many people I think.

**Comment by doud** [comment]
YEAH !!!
that rocks ...

**Comment by asual** [comment]
I will definitely add this once I finish the changes I'm currently working on.

**Comment by nyroDev** [comment]
Great, thanks!!

**Comment by asual** [comment]
I have applied the patch. Please test and let me know if you're experiencing problems.

**Comment by doud** [comment]
ok thx ... updating asap, and we'll let you know ... thx again, cool.

**Comment by nyroDev** [comment]
Looks good for me, and seems to work as expected, thanks!
