### ISSUE TITLE
In google analytics i see The page loaded twice

### ISSUE THREAD

**Issue by mscarda** [asual/jquery-address#151]
I include this code in the index and as I enter the page it looks like I visited 2 pages....

<script src="js/jquery.address-1.4.js?history=1&tracker=trackFunction&state=./&strict=0" type="text/javascript"></script>

any help pls? what i'm doing wrong?

here the code

http://pastebin.com/fBFsRBRh

**Comment by asual** [comment]
Remove the _gaq.push(["_trackPageview"]); call. It will always track the home page even if the user lands to your site using a deep link. The plugin will make the proper _trackPageview call for you automatically and because of this you see the duplicated entries.

**Comment by mscarda** [comment]
thx a lot you are super :)
