### ISSUE TITLE
After upgrading to jQuery 1.9

### ISSUE THREAD

**Issue by awsp** [asual/jquery-address#159]
I am using Chrome on Mac @version 24.0.1312.52
and after upgrading to jQuery 1.9, jQuery Address stops working.

Here are the message I got from Webkit console. 
`Uncaught TypeError: Cannot read property 'version' of undefined jquery.address.js:343`
`Uncaught TypeError: Cannot call method 'crawlable' of undefined`

**Comment by awsp** [comment]
According to jQuery, I tried add the following script, and it works when using the following script with some warnings. 
`<script src="http://code.jquery.com/jquery-migrate-1.0.0.js"></script>`

```
JQMIGRATE: jQuery.browser is deprecated jquery-migrate-1.0.0.js:29
JQMIGRATE: AJAX events should be attached to document: ajaxComplete jquery-migrate-1.0.0.js:29
JQMIGRATE: jQuery.fn.live() is deprecated jquery-migrate-1.0.0.js:29
```

**Comment by ashclarke** [comment]
+1 for 1.9 support.

**Comment by flayks** [comment]
+1 for update!

**Comment by tufik2** [comment]
I have the next error with HTML5 when i import your library:

SyntaxError: syntax error
<!DOCTYPE html>

the code of html is:

<!DOCTYPE html>
<html>
    <head>
            <link href="js/jquery/css/jquery-ui.css" rel="stylesheet" type="text/css" />
            <script src="js/jquery/jquery-1.9.1.min.js" type="text/javascript"></script>
            <script src="js/jquery/jquery-ui.js" type="text/javascript"></script>
            <script src="js/jquery/jquery.address.js" type="text/javascript"></script>
   </head>
    <body>
    </body>
</html>
