### ISSUE TITLE
Error message with latest jquery-address when run on WebKit browsers

### ISSUE THREAD

**Issue by asabhaney** [asual/jquery-address#160]
Firstly, thanks for the great plugin.

I tried to use the latest jquery-address (1.6) in conjunction with the latest jquery (1.9.0), and there seems to be a bug at line 108 in jquery-address when running on Safari (6.0.2) or Chrome (24.0):

`Uncaught TypeError: Object #<History> has no method 'popState'`

Line 108 currently is:

`_h.popState({}, '', _opts.state.replace(/\/$/, '') + (_value === '' ? '/' : _value));`

The error is thrown, but does not seem to cause any actual issues.

**Comment by asual** [comment]
Do you see this error with the provided samples? I can't reproduce it.

**Comment by asabhaney** [comment]
My apologies, works fine. It seems address-related code that I had written when using jquery-address 1.4 was causing the issue.
