### ISSUE TITLE
New style Google analytics.js not updating

### ISSUE THREAD

**Issue by mrsliv** [asual/jquery-address#177]
The new style Google Analytics (aka analytics.js) is not being updated by the plugin. 
Guessing it needs a `ga('send', 'pageview')` somewhere

**Comment by flayks** [comment]
+1 !

**Comment by panterch** [comment]
Did a quick fix for the new analytics.js here:

https://github.com/panterch/jquery-address/commit/d763e8ba4a8688273c014b3ef64324e6fda16747
