### ISSUE TITLE
Something worked in v1.2 but not in v1.3 (own encode parameter)

### ISSUE THREAD

**Issue by geki007** [asual/jquery-address#19]
I do something like this:
$.address.parameter(index,encodeURIComponent($.param(value)));
where value is an object and on change i get it back with $.deparam(value)
But in v1.3 this doesn't work because of the intern encode.
I have changed it a bit and without the encode and decode in the value function it works again.
Can you do something to get it work in the next version?
Another question is: can you implement such a function for address ... $.address.parameter(index,value) ... where value is an object. ... i think the problem here is just the get the value back not to set it (just a if and a encode).

**Comment by asual** [comment]
I just pushed a couple of encoding improvements. Please, test your code against it and let me know if you're still experiencing the trouble. If yes, then please provide a simple test case with the strings you find problematic.

**Comment by geki007** [comment]
it doesn't work like before (the url looks different) but it works.
thx

**Comment by geki007** [comment]
can you reopen it or should i fill a new bug?
the fix doesn't work in ie7
have also a testcase (where can i commit the files?)

**Comment by asual** [comment]
Can you please post here the exact values you're testing against so I can add them to the QUnit tests.

**Comment by geki007** [comment]
modified your example to a testcase http://jsfiddle.net/KuM7c/
please note:
the Address Plugin v1.3.1 have a small change ... included the deparam function but should nothing change for you and in this first testcase i don't use this function
also you can not use the testcase in jsfiddle direct i just but the code there

**Comment by asual** [comment]
Can you just post the problematic string that causes the trouble when doing $.address.parameter("paramName", "problemaricParamValue");

**Comment by geki007** [comment]
it's not ONE fix problematic Param.
the problem is following:

on a click do:
$.address.parameter('data',encodeURIComponent($.param({start:0,order:'index0'})));
$.address.update();

on a other click do:
$.address.parameter('data',encodeURIComponent($.param({start:1,order:'index1'})));
$.address.update();

the second time i call parameter it should replace the first complete 'data' but it does not (on ie7)

**Comment by asual** [comment]
The value you're passing is a combination of multiple parameters so you should better use $.address.queryString('data', $.param({start:0,order:'index0'})); The encodeURIComponent() is not needed in this case because it's handled by the plugin.

I added 2 more tests to the test suite but I wan't able to reproduce the issue in IE7.

**Comment by geki007** [comment]
i thougt also it should work like you say BUT it didn't
do following
put a console.log(names); in line 691

i get ["data", "order"] ... i think this should only ["data"]

and param of order is UNDEFINED!
param of data is correct

(this is not IE only)

**Comment by geki007** [comment]
a small testcase:
$(function(){
        $.address.parameter('data',$.param({start:0,order:'index0'}));
        $.address.update();
        alert($.address.parameterNames());
    });
2 parameterNames?!

**Comment by asual** [comment]
Thanks! Try the lastest version. Should work better now.

**Comment by geki007** [comment]
yes works better, BUT not perfect :)

take the last small testcase and press f5 than you get back the 2 parameternames (ONLY in IE7)

in IE7 it looks like IE converts the string itself?!
i see it correct "a.html#/?data=start%3D0%26order%3Dindex0" ... before the alert and after it i see "a.html#/?data=start=0&order=index0"

**Comment by asual** [comment]
Please, try to run the test suite that ships with the project. Add more tests if you think it's needed and make sure the cache is cleared.

**Comment by geki007** [comment]
don't know how it work's but i will try :)

**Comment by asual** [comment]
Download the project and open the test/index.html in your browser.

**Comment by geki007** [comment]
not very hard :)
this testcase fails in IE7 but works in chrome

<pre>
asyncTest('PARAM Data test', function() {
    var data = {start:0,index:'index0'};
    $.address.parameter('data',$.param(data));
    equals($.address.parameter('data'),$.param(data),'now');
    setTimeout(function() {
        equals($.address.parameter('data'),$.param(data),'after 200ms');
        start();
    }, 200);
});
</pre>

**Comment by geki007** [comment]
another testcase for you (i don't know how i should make this without making 2 files)

run this test 1 time with jquery.address-1.3.1.min.js included (fails on ie7)
and the second time without address (works on ie7)
i think you have somewhere a bad decode

hope helps!

<pre>
asyncTest('IE7 hash test', function() {
    var data = {start:0,index:'index0'};
    window.location.hash='data='+encodeURIComponent($.param(data));
    setTimeout(function() {
        equals(window.location.hash,'#data=' + encodeURIComponent($.param(data)),'after 100ms');
        start();
    }, 100);
});
</pre>

**Comment by geki007** [comment]
looks like http://github.com/asual/jquery-address/issues/#issue/23 could also fix this issue

**Comment by asual** [comment]
Everything should work fine now.

**Comment by geki007** [comment]
thx
