### ISSUE TITLE
special characters in a parameters

### ISSUE THREAD

**Issue by teimatini** [asual/jquery-address#20]
If you add a parameter with a special character in the value string, url is broken.

Ej,
& characte
$.address.parameter('par', 'a&b');
# character

$.address.parameter('par', 'a#b');

there should be lots of cases with this behavior

THNKS!

**Comment by asual** [comment]
I pushed a fix for the case you reported. Please, test!

**Comment by teimatini** [comment]
seems to be working fine
THNKS!

**Comment by flyliu33** [comment]
@teimatini which version you use, I found the question in version 1.6
