### ISSUE TITLE
Bug: value check not sufficient (value must be a string)

### ISSUE THREAD

**Issue by bippesbrandao** [asual/jquery-address#26]
If the value is an integer (e.g. $.address.value(1)), string functions like substr, split etc. will fail.
Doing a value.toString() fixes this bug for me.

value: function(value) {
                if (value !== UNDEFINED) {
                    if (!isNaN(value) ) value=value.toString();
                    ...

best regards
Arne

**Comment by asual** [comment]
It's now fixed in the _strict private function.
