### ISSUE TITLE
State bug on IE9.0.8023.60000 Platform Preview

### ISSUE THREAD

**Issue by laukstein** [asual/jquery-address#28]
On IE9.0.8023.60000 Platform Preview http://.../jquery/address/samples/state/contact and http://.../jquery/address/samples/state/#/contact opens `Home content` and not `Contact content`.

**Comment by asual** [comment]
The sample works fine for me in the official Beta (9.0.7930.16406) but behaves very strange in the Platform Preview 7 (9.0.8023.60000). I suppose that this might be related to the lack of address bar or something specific to this type of IE window. 

Lets see how it will behave in the next standard build.

**Comment by laukstein** [comment]
O.K. Lets look forward.
