### ISSUE TITLE
Firefox 3.6.13, Firebug 1.6 `State`: on firs try `Open Link in New Tab` has 3 GET html request

### ISSUE THREAD

**Issue by laukstein** [asual/jquery-address#29]
Firefox 3.6.13, Firebug 1.6 `State`: on firs try `Open Link in New Tab` has 3 GET html requests. Does it needs to be so? Screenshot in http://goo.gl/4v1ho .

For `Express` it works fine.

**Comment by asual** [comment]
All the links in the pushState samples do not contain hash fragments. This means that opening a new tab in Firefox 3.6 creates the following sequence:
1. The browser requests and loads a /portfolio page. 
2. Support for pushState is not detected and the plugin then requests the /#/portfolio page.
3. When the /#/portfolio page is loaded the proper content is again requested from /portfolio using Ajax.

**Comment by laukstein** [comment]
Is there some way to make for it just one Ajax request?

**Comment by asual** [comment]
It should be possible in Firefox 4.

**Comment by laukstein** [comment]
It does not mean you have a issue for that, because some still will continue to use old browsers and it will slow down Ajax request for them because of this bug.
