### ISSUE TITLE
*minor* warning: ']' to end attribut-selectors expected, but ':' found.

### ISSUE THREAD

**Issue by windwerfer** [asual/jquery-address#3]
great work with your plugin!!
its easy to use+gives me all i want ;-)

i'm just such a penny pincher that i write to you the little warning i get when i use your script (mozilla+chrome tested):
in line 172 of the Address Plugin v1.1 there seems to be a problem with jquery 1.4.2
it doesnt except the ':'  (_____$('a[rel*=address:]').address();_____) their, since normaly its used to start a filtered statment ...
i fixed it by add a double backslash infront of it

$('a[rel*=address\:]').address();

worked for me... no warnings anymore ;-) 

other than that: thanks man!!! really good plugin.
hope you find some easter eggs ;-) yours thomas

**Comment by asual** [comment]
The problematic line is now replaced by the following:
$('a').filter('[rel*=address:]').address();
