### ISSUE TITLE
IE8 JS error in case when Cufon is used (VML elements are in DOM)

### ISSUE THREAD

**Issue by Lukasz401** [asual/jquery-address#39]
Internet Explorer 8 and 7 raise JS error: 

"attribute only valid on v:image" in line 80 of jquery.address-1.3.1.js

It happens when on the same page Cufon is used for font rendering. Cufon on IE8/7 uses VML for rendering. The problem is that VML elements raise such exception when src  attribute is accessed (and for nodeName also).

I made ad-hoc solution for my needs by adding such condition at the beginning of _search function:

if (el.nodeName.toLowerCase() == 'cufon') return '';

but this is far from general solution.

Greetings,
Lukasz

**Comment by jmoiron** [comment]
This also happens when using jquery-address when using PIE.js for IE compatability, as I'd imagine it is using VML elements for much of its stuff as well.

The fix I came up with (perhaps more general) was to change, in _search (line 82 in my version):

```
if (el.childNodes[i].src) {
```

to:

```
if ('src' in el.childNodes[i] && el.childNodes[i].src) {
```

**Comment by Reggino** [comment]
The fix you just made doesn't fix the problem in IE7/8. A better solution would be to not travel the entire dom tree but just look for the last script tag and get the src attrbute from that. So change line 318 into:

```
_url = $('script:last').attr('src'),
```

And drop the _Search function on line 77

**Comment by asual** [comment]
Thanks! I will check your proposal. The _search function is a workaround for a more trivial getElementsByTagName solution that was causing Firefox issues in the past. 

I have to check if $('script:last') is working before the document DOM is ready and it's not causing the issues mentioned above.
