### ISSUE TITLE
Encoding problem in parameter()

### ISSUE THREAD

**Issue by cturner81** [asual/jquery-address#40]
I'm not entirely sure how you are encoding/parsing data sent to the parameter function, but there seems to be a problem in that there's no way to differentiate a + and a space once it's sent through parameter().  For example:

$.address.parameter('test', value test');
$.address.parameter('test', 'value+test');

both encode to the identical value "value+test", where one would expect something more like "value%20test" and "value%2Btest" or similar.  Just any way to differentiate those two values once they've been dropped into the URI.

**Comment by asual** [comment]
The plus is a tricky symbol and it's used by jQuery for space encoding. Now you should see "value+test" and "value%2Btest" in the address bar. Check the updated test suite for more info.
