### ISSUE TITLE
Latest jquery.address.js validating failed

### ISSUE THREAD

**Issue by laukstein** [asual/jquery-address#43]
If you try to validate [latest jquery.address.js](https://github.com/asual/jquery-address/raw/master/src/jquery.address.js) trough [jslint.com](http://www.jslint.com/), you have lots of errors there.

**Comment by asual** [comment]
The JSLint validation is included in the build process similarly to the way it's done in the jQuery build. JSLint has various options and both jQuery and the Address plugin use the same configuration. Both produce some errors with the default options on jslint.com.

**Comment by laukstein** [comment]
I have noticed Firebug Console warnings on checking jQuery syntax with [jQuery Lint](https://github.com/jamespadolsey/jQuery-Lint).

**Comment by asual** [comment]
I just pushed a minor optimization as a result of the jQuery Lint check. It's not correct about the .trigger(event) invocation.

**Comment by laukstein** [comment]
O.K. I'll keep that in mind.
