### ISSUE TITLE
Hash based links not working for HTML5 history.pushState compatible browsers

### ISSUE THREAD

**Issue by dlee** [asual/jquery-address#50]
If I save a deep link in Firefox 3.6 and load it in Chrome 9, the page will load as if I loaded the link with the hash stripped.

The other way works fine, where I load a non-hashed link in Firefox 3.6 and it redirects to the hashed version.

To reproduce, try loading http://www.asual.com/jquery/address/samples/state/#/about in FF 3.6 and then in Chrome 9.

**Comment by balupton** [comment]
This use case is covered by an alternative to jQuery Address called History.js - http://github.com/balupton/history.js

**Comment by asual** [comment]
This is similar to Issue 69 and should be fixed now.
