### ISSUE TITLE
"Syntax error, unrecognized expression: [rel*=address:]" with jQuery 1.5

### ISSUE THREAD

**Issue by tianon** [asual/jquery-address#54]
Using jQuery 1.5 and the latest code, I get the following exception:
Syntax error, unrecognized expression: [rel*=address:]

The exception is fixed when line 264 is changed from:

```
                    if (el.is('[rel*=address:]')) {
```

To:

```
                    if (el.is('[rel*="address:"]')) {
```

(Notice the double quotes added.)

I would guess that Sizzle changed how they parse *= selectors in the latest jQuery.  Also, the change above should be backwards compatible with older versions of jQuery.

**Comment by tianon** [comment]
See also http://api.jquery.com/attribute-contains-selector/

Ah crap, sorry, didn't mean to close this issue, and of course I can't reopen it...

**Comment by asual** [comment]
Thanks! It's fixed now.

**Comment by tianon** [comment]
You bet, glad I could help. :)

**Comment by tianon** [comment]
Similarly, on line 214 you've got:

```
                            _value = win[ID] !== UNDEFINED ? decode(win[ID]) : '';
```

But this line causes an error in IE 7, so I think you meant:

```
                            _value = win[ID] !== UNDEFINED ? _decode(win[ID]) : '';
```

(Which appears to be working as expected.)

**Comment by asual** [comment]
I just changed it to 

```
 _value = win[ID] !== UNDEFINED ? $.address.decode(win[ID]) : '';
```

which should work fine.

**Comment by tianon** [comment]
Perfect, thanks. :)

**Comment by yeshwanthmn** [comment]
Error: Syntax error, unrecognized expression: [data-item-id=Prod__92__TA1__92__Indication1__92__Phase1__92__ONCO2037WDR02__92__Safety Data]

$("#simple-treeview").find("[data-item-id="+$rootScope.key+"]").focus().addClass("dx-state-focused");
