### ISSUE TITLE
Behaviour of $.address.parameter(name, value, append)

### ISSUE THREAD

**Issue by ivanrdzmrt** [asual/jquery-address#57]
Any one knows why when you instance twice $.address.parameter(name, value, append) method it produces two changeEvent identic??

My code is like this:

$.address.parameter ('submodulo', id_modulo, false);
$.address.parameter ('parametros', params, false);
$.address.update();

And then, its produces the same change event twice...

What is the way for pass parameters in array mode and... it can solve this?

**Comment by ivanrdzmrt** [comment]
My problem is that I want to have more than one module active at the same time, so when I load the main container and put its value at address, then I need to load a secondary module and store it´s state:

1- First, on load one module

$.address.title(id_modulo);
$.address.value(id_modulo);
($.address.queryString(params);)
$.address.update();

URL= http://www.someprettyurl.com#/id_module

2- Second, then load any submodule

$.address.parameter ('submodulo', id_modulo, false); 
$.address.parameter ('parametros', params, false); 
$.address.update();

URL= http://www.someprettyurl.com#/id_module?submodulo=campaign&parametros=id=42

My problem is that the  $.address.change(function(event)) is called twice after calling $.address.update(); when loading a secondary module aka submodule, and the event have the same detail info.

```
     });  
```

**Comment by asual** [comment]
Every time you set a parameter a change event should be fired and the address bar should be updated. If you want to set a number of parameters and then have a single event then you should do something like this:

```
    $.address.autoUpdate(false)
        .value('/')
        .parameter('p1', 'a#b')
        .parameter('p2', 'a&b')
        .autoUpdate(true)
        .update();
```

**Comment by ivanrdzmrt** [comment]
It seems to fire change event more than twice, one time  with parameter and values and two more times without parameters....

Exist any other way to implement this functionality? Of course, I can implement a boolean var to inform me if the event is fired twice but I think is not the more polite design.

 Suggestions?

**Comment by asual** [comment]
Did you try the code I posted above? Also check the Accordion sample which uses the disabled autoUpdate setting.

**Comment by ivanrdzmrt** [comment]
Yes of course, with multiple variations but it seems impossible to make it happen. For the moment I will let it with only upper-lever modules functionality and at future I will give it another try.

**Comment by Akaryatrh** [comment]
I had the same problem, and the trick with auto updating to false worked like a charm. Still, to me it's just a workaround, that would have been great if we could use .parameter() this way :
$.address.parameter({"param1":"value1","param2":"value2"});

Oh and just a word about it : what is the option "append" for ? (the documentation doesn't tell a lot about it)

Anyway, thx a lot for this great plugin :)
