### ISSUE TITLE
How to make $.address.change() only work when there is a hash tag?

### ISSUE THREAD

**Issue by trusktr** [asual/jquery-address#60]
For example, when someone visits my page at http://bettafootwear.com/CrownYourFeet/, the initial content loads, then Address proceeds to load more content.

I want it to load content _only_ when the browser's initial URL contains a hash.

For example, I want it to load content only when my users go to a URL like this one:
http://bettafootwear.com/CrownYourFeet/#/category/blog

Also, if my users go to http://bettafootwear.com/CrownYourFeet/, then click on a link, the URL address will be come something like:
http://bettafootwear.com/CrownYourFeet/#/category/blog

And if they hit the back button, the URL should return to http://bettafootwear.com/CrownYourFeet/ and only in that case reload content from the base URL.

Am I missing something?

You can see the code I'm using here:
http://bettafootwear.com/CrownYourFeet/wp-content/themes/betta_v2/js/wordpress_ajax.js

Thanks!

**Comment by francishogue** [comment]
I think I'm having the same issue - any development on this?

**Comment by asual** [comment]
Sounds like you can achieve this with some custom logic like this:

```
var initialized = false;

$.address.change(function(e) {
    if (initialized || e.value != '/') {
        // do the content loading
    }
    initialized = true;
});
```

**Comment by trusktr** [comment]
Thanks for the reply. I came up with something like that on my own after posting this actually. I'mma play around with it and see what I come up with. I'll post my actual solution when it's done. :D
