### ISSUE TITLE
jQuery 1.5: [firebug] uncaught exception: Syntax error, unrecognized expression: [href*=mydomain.com]

### ISSUE THREAD

**Issue by RafaLibrenz** [asual/jquery-address#63]
With jQuery 1.5, using Address crawling, i get an error in firebug:

```
uncaught exception: Syntax error, unrecognized expression: [href*=mydomain.com]
```

And pages don't load, links don't work.

If I make a downgrade to jQuery 1.4.4, everythig runs fine.

If I run this at localhost (with jQuery 1.5), everything runs fine.

The error is only when hosted in a web domain.

Here's a live example: http://impulse.im/clean/jq1_5/

**Comment by asual** [comment]
Can you please check the latest version of src/jquery.address.js. I believe this was fixed after the 1.3.2 release.

**Comment by RafaLibrenz** [comment]
But I'm using the 1.3.2 release in this page. What's wrong? I don't understand.

**Comment by asual** [comment]
This is the change needed:

https://github.com/asual/jquery-address/commit/f6ffdb4ec0fbbae1a8e9d91ad90f021a92687521

**Comment by RafaLibrenz** [comment]
Yes, now the issue is fixed!!! Thank you!!! :)
