### ISSUE TITLE
Incorrect encoding-decoding

### ISSUE THREAD

**Issue by varunwy** [asual/jquery-address#66]
plus character (+) and space character (' ') both are decoded into plus(+)
by the plugin.

See the two code samples below.

Sample1:
var str_plus = "one two";  
$.address.parameter('test', str_plus);
alert($.address.parameter('test'));

alerts one+two
# 

Sample2:
var str_space = "one+two";
$.address.parameter('test', str_space);
alert($.address.parameter('test'));

alerts one+two

**Comment by asual** [comment]
The internal de/encoding is now completely removed which means that this problem should be gone. Let me know if it still exists.
