### ISSUE TITLE
trailing slash problem / webkit / scrolling

### ISSUE THREAD

**Issue by honk31** [asual/jquery-address#67]
hi

i had an issue with the trailing slash in safari (webkit).
when the site was scrolled down a little and i clicked a link back to home (/)
the url was http://example.com/#
but the # at the end made safari act like an anchor-link, so it jumpes back up to the top of the page.

in firefox the url doesnt look like in safari, its 
http://example.com/#/
i took me a whole day to realize that the problem was the missing trailing slash.

so in line 617 i changed
_l.hash = '#' + _crawl(_value, TRUE);

to
_l.hash = '#/' + _crawl(_value, TRUE).substr(1);

maybe this isnt the best solution, but this works form me now.

the NOT scrolling was so important for me, because the whole site operates through scrolling, all content is loaded by ajax, so i defenetly needed the "old" and correct position..

hope this helps..

**Comment by asual** [comment]
The correct URL should be http://example.com/# and not http://example.com/#/. There was a recent issue that was producing the second result and is now fixed. The first URL is creating scroll problems and therefore the plugin provides a $.address.wrap(true) option that should take care of it.
