### ISSUE TITLE
State bug for latest jquery.address.js

### ISSUE THREAD

**Issue by laukstein** [asual/jquery-address#69]
State bug for latest jquery.address.js - 
-    works fine with `jquery.address.js?state=/jquery/address/samples/state`
-    does not work with `jquery.address.js` `$.address.state('/jquery/address/samples/state').init(function(){...`.

You can check it on www.asual.com/jquery/address/samples/state/

Url rewrite from `/about` to `/#/about` and from `/#/about` to `/about` for browsers that support `pushState` **is broken**.

localhost/jquery-address/samples/state/about has no rewrite and on `event click` 'Portfolio' it returns **wrong url** localhost/jquery-address/samples/state/about#/portfolio

**Comment by asual** [comment]
Should work fine now. Thanks!

**Comment by laukstein** [comment]
Thanks!
