### ISSUE TITLE
Google proposal to make ajax crawlable

### ISSUE THREAD

**Issue by vmortega** [asual/jquery-address#7]
Hi!, have you read this?

http://googlewebmastercentral.blogspot.com/2009/10/proposal-for-making-ajax-crawlable.html
http://docs.google.com/present/view?id=dc75gmks_120cjkt2chf

maybe you can implement #! instead of # by default or add an option to activate it

thanks

**Comment by asual** [comment]
It seems like you have missed one of the biggest features of the 1.2 release. 
Please. check the provided samples and our blog for more information.
