### ISSUE TITLE
Script not working.

### ISSUE THREAD

**Issue by Asarew** [asual/jquery-address#73]
Hey, first of all Love you script.
But i have a little problem, when i click a link the url in the address bar changes (and thats a good thing), but when i use that link to go to the same page it just goes to the original page.
the only thing i added was:

$('a').click(function() {  
    $.address.value($(this).attr('href'));  
});

do i have to do something extra to make deep linking posible ?

**Comment by asual** [comment]
You need to bind the change event that the plugin fires.

**Comment by Asarew** [comment]
oww sorry,
think i had to say that i figured it out by my self, but thanks anyway ;-)

**Comment by agasani** [comment]
would you please say what you were doing differently?

**Comment by agasani** [comment]
got it! bind the change event to the address change. In other words, do the ajax in the $.address.change(function (e) {} callback. otherwise, there is no way the script we'll be aware of your magic..
