### ISSUE TITLE
Removes last slash with a query string

### ISSUE THREAD

**Issue by fire015** [asual/jquery-address#75]
I am using this:

```
$('div.search-left form').submit(function(){
    if (validateSearchForm()) {
        var url = $(this).attr('action') + '?' + $(this).serialize();
        $.address.value(url);
    }
    return false;
});
```

However when the form is submitted and the address changes instead of...

http://site.com/search/?q=test

It does:

http://site.com/search/http://site.com/search?q=test

i.e. its removing the forward slash on /search/ so its not correctly replacing the URL.

Just using the default settings with a state set to http://site.com/search/

**Comment by asual** [comment]
Was that a bug with your code or you found a workaround for the plugin issue?

**Comment by fire015** [comment]
Was a bug with my code, it should only have passed '?' + $(this).serialize() as its not running through the address function which tries to stop that with regex.
