### ISSUE TITLE
not working with jquery 1.6

### ISSUE THREAD

**Issue by clarkbox** [asual/jquery-address#79]
see this jsfiddle >
http://jsfiddle.net/Wh7uS/

change to jquery  <1.6 and things work fine.

no exceptions. just fails silently with jquery 1.6

**Comment by estoner** [comment]
+1, I'm seeing the same behavior.

**Comment by findzen** [comment]
Same here. External / internal change callbacks are not firing.

**Comment by posabsolute** [comment]
External / internal change callbacks are not firing with the last version for me. 
using the bind method
$.address.externalChange work
 $.address.bind('externalChange' do not work
