### ISSUE TITLE
Base URL with query string

### ISSUE THREAD

**Issue by nauthiz693** [asual/jquery-address#8]
I'm not really sure if this is an issue or if it's by design.. I have a page whose url looks like this: http://www.domain.com/folder?page=1

There is a link on the page to "/folder" and when the address plugin loads, it's url gets replaced with "#".

It's in the _unescape function, where it strips the base from internal urls, and then checks if there's anything remaining - but the base doesn't include the query string.  Is this by design?  

Thanks!

**Comment by asual** [comment]
I wasn't able to reproduce the problem. I created the following page and tested it using http://localhost/test.html?page=3

```
<!DOCTYPE html>
<html>
    <head>
        <title>jQuery Address</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <script type="text/javascript" src="jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="jquery.address-1.2.min.js"></script>
    </head>
    <body>
        <p>
            <a href="test.html">Base Link</a>
            <a href="test.html?page=1">Page 1</a>
            <a href="test.html?page=2">Page 2</a>
        </p>
    </body>
</html>
```

**Comment by nauthiz693** [comment]
Sorry my bad, add a preceding slash to the hrefs of all three links and you should see the problem..

**Comment by asual** [comment]
This modification of the href is now restricted only to pages that use the Crawling mechanism. It doesn't support query parameters different from _escaped_fragment_ for now so such a change will be performed by design. I will try to make it more flexible in the near future.
