### ISSUE TITLE
Collision between deep links and virtual links

### ISSUE THREAD

**Issue by jksmithing** [asual/jquery-address#87]
Say User A has a browser with HTML5 state support. They send this link to User B:

`http://domain.tld/node`

User B -- whose browser does not have state support -- opens the link, navigates to another node, and sends the link back to User A:

`http://domain.tld/node#!/another-node`

When user A opens the link, the `$.address value()` is equal to `/node#/another-node` instead of `/another-node`. (Curiously the "!" is dropped from the hash value.)

Is this the expected behavior?

I noticed that the virtual address is automatically translated on initialization to a real deep link if there's not already a deep link value. That is:
`http://domain.td/#!/another-node`
will be translated to:
`http://domain.td/another-node`
on an state-enabled browser -- without adding another history entry.

Thanks so much for your consideration.

**Comment by jksmithing** [comment]
After more thought, I think this is an implementation issue. I do what Twitter does:
On a non-state-enabled browser,
`http://domain.tld/node`
is replaced with
`http://domain.tld/#!/node`

**Comment by qwertzy** [comment]
Can you please tell us how you replaced the url? mod_rewrite or is it javascript based?
Having the same issue with ff4 (html5 support) and ff3

**Comment by jksmithing** [comment]
Yeah it wasn't obvious to me, either. I'm pretty sure that mod_rewrite isn't aware of hash values, so I ended up having to use JS. The `location.replace()` method allows you to load a new URI without adding a history entry. So what I do is compare the actual address against what it should be, and replace it if it's incorrect:

```
var addressValue = $.address.value(),
    initPath = window.location.pathname.replace(stateBasePath, ""),
    newLocation = baseUrl +stateBasePath + (supports_history_api() ? "" : "/#!") + (addressValue != "/" ? addressValue : initPath + window.location.search);
if (newLocation != window.location.href) {
    window.location.replace(newLocation);
}
```

**Comment by qwertzy** [comment]
Thanks for the code. Where do you put it? When I put it in the change event it will end in an endless loop changing from /#!page to /page and back again.

**Comment by jksmithing** [comment]
Basically it's the first JS that gets executed, as I want to replace the URI before anything else starts to load, to make the transition as seamless as possible.  So, after you include jQuery Address, but before any other code is executed, and outside of a document ready function.

I suppose you could even execute it before `$.address` was loaded, but you'd have to write your own function for extracting the `$.address.value()`.

There's a couple variables that I didn't define above:
- `stateBasePath` is equivalent to the value you would use for `$.address.state()` (just an empty string if the site is located at the document root)
- `baseUrl` is the URI protocol and domain, e.g. `http://domain.tld` (no trailing slash)
- `supports_history_api()` is a little ditty taken from [Mark Pilgrim](http://diveintohtml5.org/detect.html)
