### ISSUE TITLE
Opera 11.11 pushState and replaceState!

### ISSUE THREAD

**Issue by laukstein** [asual/jquery-address#89]
Opera 11.11 (Opera Presto 2.8) has HTML5 Session History & Navigation support http://www.opera.com/docs/specs/presto28/sessionhistorynav/ , but it still does not work in latest jQuery Address State. Unfortunately it returns hash fallback.

**Comment by asual** [comment]
Just downloaded and tried Opera/9.80 (Macintosh; Intel Mac OS X 10.6.7; U; en) Presto/2.8.131 Version/11.11. 

It simply doesn't have pushState support yet. I get the following:
Uncaught exception: TypeError: 'window.history.pushState' is not a function

**Comment by jacksmith117** [comment]
Will be supported in Opera 11.50+

**Comment by laukstein** [comment]
Then seems like Opera team has publicized not true information in http://www.opera.com/docs/specs/presto28/sessionhistorynav/

**Comment by jacksmith117** [comment]
It seems that not all features of Presto are supported immediately by the browser itself. It took some time for them to integrate it into the browser.

**Comment by laukstein** [comment]
It's supported in Opera 11.50. You can see the successful result in http://lab.laukstein.com/ajax-seo/
