### ISSUE TITLE
Init Event - Google Chrome

### ISSUE THREAD

**Issue by TommasoBelluzzo** [asual/jquery-address#98]
This is my code:

$(window).load(function()
{
     $('#navigation a').address();
     $.address.init(function() { alert('fired'); });
});

Alert never pops up. I'm using:
- Google Chrome 12.0.742.122m
- jQuery 1.6.1
- jQuery Address 1.4

Anything wrong with it?

**Comment by ualtinok** [comment]
I have the same problem:

Chrome 13.0.782.107
jQuery 1.6.2
jQuery Address 1.4

**Comment by beaur** [comment]
I'm also seeing problems.
Chrome 14 Mac, 
jQuery 1.6.1

**Comment by fed239** [comment]
Is this fixed? This makes us a lot of troubles.
